language: node_js
node_js:
 - "10.9.0"
dist: trusty
sudo: required

branches:
  only:
    - master
    - sonarqube

addons:
  chrome: stable
  sonarcloud: true

before_script:
  - sudo wget $SONAR_KEYSTORE -O /usr/bin/local.keystore
  - npm install -g @angular/cli

cache:
  npm: true
  directories:
    - node_modules

env:
  - SONAR_SCANNER_OPTS=-Djavax.net.ssl.keyStore=/usr/bin/local.keystore

script:
  - npm run lint
  - npm run build:lite
  - npm run test
  - sonar-scanner -D sonar.projectKey=$SONAR_PROJECTKEY -D sonar.host.url=$SONAR_HOST_URL -D sonar.login=$SONAR_TOKEN -X
